spring.config.import=optional:file:.env[.properties]

spring.application.name=${SPRING_APPLICATION_NAME}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED}
spring.flyway.locations=${SPRING_FLYWAY_LOCATIONS}

mybatis.mapper-locations=${MYBATIS_MAPPER_LOCATIONS}
mybatis.type-aliases-package=${MYBATIS_TYPE_ALIASES_PACKAGE}
mybatis.configuration.map-underscore-to-camel-case=${MYBATIS_CONFIGURATION_MAP_UNDERSCORE_TO_CAMEL_CASE}
mybatis.configuration.default-enum-type-handler=${MYBATIS_CONFIGURATION_DEFAULT_ENUM_TYPE_HANDLER}
# logging.level.com.example.swiftroute.order.infrastructure.persistence.OrderMapper=TRACE
mybatis.type-handlers-package=${MYBATIS_TYPE_HANDLERS_PACKAGE}
