spring.application.name=swiftroute

spring.datasource.url = jdbc:postgresql://localhost:5432/swiftroute
spring.datasource.username = swiftroute
spring.datasource.password = swiftroute
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.swiftroute.order.domain.model
mybatis.configuration.map-underscore-to-camel-case=true
# logging.level.com.example.swiftroute.order.infrastructure.persistence.OrderMapper=TRACE