spring.application.name=swiftroute

spring.datasource.url = jdbc:postgresql://localhost:5432/swiftroute
spring.datasource.username = swiftroute
spring.datasource.password = swiftroute
spring.data.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true


